//package com.lt.journey.model;
//
//import java.util.Arrays;
//import java.util.HashMap;
//
//public class Hotel {
//	private String rating;
//	private String catPathKey;
//	private String dislikeCount;
//	private String ratingCount;
//	private String avgPrice;
//	private String commentCount;
//	private String facilities;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	private String openDate;
//	
//}
